### ISSUE TITLE
corbo core error file missing

### ISSUE THREAD

**Issue by Thedush** [rst-tu-dortmund/mpc_local_planner#12]
CMake Error at mpc_local_planner/mpc_local_planner/CMakeLists.txt:206 (add_dependencies):
  The dependency target "corbo_core" of target "mpc_local_planner_utils" does
  not exist.

CMake Error at mpc_local_planner/mpc_local_planner/CMakeLists.txt:206 (add_dependencies):
  The dependency target "corbo_systems" of target "mpc_local_planner_utils"
  does not exist.

**Comment by croesmann** [comment]
I guess you need to install [control_box_rst](https://github.com/rst-tu-dortmund/control_box_rst/wiki/Build-from-Source) first.

**Comment by croesmann** [comment]
I'll close this for now but feel free to add further comments.

**Comment by MichelleHusbands** [comment]
Hello, I am getting the error that <corbo-core/time_series.h> does not exists. I have control_box_rst installed and checked that the file exists. Do you know how to solve it? I've been driving me crazy for the past two days.
