### ISSUE TITLE
Use example get the "move_base-3" error.

### ISSUE THREAD

**Issue by Tao-Sheng** [rst-tu-dortmund/mpc_local_planner#37]
Hi,Christoph Rosmann.
I use origion source and launch "roslaunch mpc_local_planner_examples carlike_minimum_time.launch" ,get [move_base-3] error in the end.
I have installed all dependencies and catkin_make successfully.I have searched "move_base-3" error for a long time but get nothing.
Could you please help me solve this issue,thank you.
PS:ubuntu 18.04  ros melodic

[ INFO] [1618374390.653249419]: Loading map from image "/home/nical/mpc_ws/src/mpc_local_planner/mpc_local_planner_examples/maps/maze.png"
[ INFO] [1618374390.687995636]: Subscribed to map topic.
[ INFO] [1618374391.097138854, 0.300000000]: Read a 200 X 200 map @ 0.050 m/cell
[ INFO] [1618374391.372478110, 0.500000000]: Received a 200 X 200 map @ 0.050 m/pix

[ INFO] [1618374391.375526743, 0.500000000]: Initializing likelihood field model; this can take some time on large maps...
[ INFO] [1618374391.380459469, 0.500000000]: Done initializing likelihood field model.
[ INFO] [1618374392.398645250, 1.600000000]: global_costmap: Using plugin "static_layer"
[ INFO] [1618374392.421153095, 1.600000000]: Requesting the map...
[ INFO] [1618374392.591438304, 1.800000000]: Resizing costmap to 200 X 200 at 0.050000 m/pix
[ INFO] [1618374392.691358487, 1.900000000]: Received a 200 X 200 map at 0.050000 m/pix
[ INFO] [1618374392.699597269, 1.900000000]: global_costmap: Using plugin "obstacle_layer"
[ INFO] [1618374392.701547553, 1.900000000]:     Subscribed to Topics: laser_scan_sensor
[ INFO] [1618374392.712448318, 1.900000000]: global_costmap: Using plugin "inflation_layer"
[ INFO] [1618374392.736464387, 1.900000000]: local_costmap: Using plugin "static_layer"
[ INFO] [1618374392.738583883, 1.900000000]: Requesting the map...
[ INFO] [1618374392.739329529, 1.900000000]: Resizing static layer to 200 X 200 at 0.050000 m/pix
[ INFO] [1618374392.789361141, 2.000000000]: Received a 200 X 200 map at 0.050000 m/pix
[ INFO] [1618374392.792265019, 2.000000000]: local_costmap: Using plugin "obstacle_layer"
[ INFO] [1618374392.793613181, 2.000000000]:     Subscribed to Topics: laser_scan_sensor
[ INFO] [1618374392.816575793, 2.000000000]: Created local_planner mpc_local_planner/MpcLocalPlannerROS
[ INFO] [1618374392.821068506, 2.000000000]: Footprint model 'line' (line_start: [0,0]m, line_end: [0.4,0]m) loaded for trajectory optimization.
[move_base-3] process has died [pid 7319, exit code -11, cmd /home/nical/mpc_ws/devel/lib/move_base/move_base __name:=move_base __log:=/home/nical/.ros/log/95c63164-9cd9-11eb-a37b-e45e37a829c9/move_base-3.log].
log file: /home/nical/.ros/log/95c63164-9cd9-11eb-a37b-e45e37a829c9/move_base-3*.log

**Comment by ruficol** [comment]
Hello, Toushine.
I also encountered the same problem, have you solved it yet?
 If you successfully solve it, can you tell me the solution? thank u.

**Comment by ruficol** [comment]
> Hi,Christoph Rosmann. I use origion source and launch "roslaunch mpc_local_planner_examples carlike_minimum_time.launch" ,get [move_base-3] error in the end. I have installed all dependencies and catkin_make successfully.I have searched "move_base-3" error for a long time but get nothing. Could you please help me solve this issue,thank you. PS:ubuntu 18.04 ros melodic
> 
> [ INFO] [1618374390.653249419]: Loading map from image "/home/nical/mpc_ws/src/mpc_local_planner/mpc_local_planner_examples/maps/maze.png" [ INFO] [1618374390.687995636]: Subscribed to map topic. [ INFO] [1618374391.097138854, 0.300000000]: Read a 200 X 200 map @ 0.050 m/cell [ INFO] [1618374391.372478110, 0.500000000]: Received a 200 X 200 map @ 0.050 m/pix
> 
> [ INFO] [1618374391.375526743, 0.500000000]: Initializing likelihood field model; this can take some time on large maps... [ INFO] [1618374391.380459469, 0.500000000]: Done initializing likelihood field model. [ INFO] [1618374392.398645250, 1.600000000]: global_costmap: Using plugin "static_layer" [ INFO] [1618374392.421153095, 1.600000000]: Requesting the map... [ INFO] [1618374392.591438304, 1.800000000]: Resizing costmap to 200 X 200 at 0.050000 m/pix [ INFO] [1618374392.691358487, 1.900000000]: Received a 200 X 200 map at 0.050000 m/pix [ INFO] [1618374392.699597269, 1.900000000]: global_costmap: Using plugin "obstacle_layer" [ INFO] [1618374392.701547553, 1.900000000]: Subscribed to Topics: laser_scan_sensor [ INFO] [1618374392.712448318, 1.900000000]: global_costmap: Using plugin "inflation_layer" [ INFO] [1618374392.736464387, 1.900000000]: local_costmap: Using plugin "static_layer" [ INFO] [1618374392.738583883, 1.900000000]: Requesting the map... [ INFO] [1618374392.739329529, 1.900000000]: Resizing static layer to 200 X 200 at 0.050000 m/pix [ INFO] [1618374392.789361141, 2.000000000]: Received a 200 X 200 map at 0.050000 m/pix [ INFO] [1618374392.792265019, 2.000000000]: local_costmap: Using plugin "obstacle_layer" [ INFO] [1618374392.793613181, 2.000000000]: Subscribed to Topics: laser_scan_sensor [ INFO] [1618374392.816575793, 2.000000000]: Created local_planner mpc_local_planner/MpcLocalPlannerROS [ INFO] [1618374392.821068506, 2.000000000]: Footprint model 'line' (line_start: [0,0]m, line_end: [0.4,0]m) loaded for trajectory optimization. [move_base-3] process has died [pid 7319, exit code -11, cmd /home/nical/mpc_ws/devel/lib/move_base/move_base __name:=move_base __log:=/home/nical/.ros/log/95c63164-9cd9-11eb-a37b-e45e37a829c9/move_base-3.log]. log file: /home/nical/.ros/log/95c63164-9cd9-11eb-a37b-e45e37a829c9/move_base-3*.log

Hello, Toushine.
I also encountered the same problem, have you solved it yet?
 If you successfully solve it, can you tell me the solution? thank u.

**Comment by Tao-Sheng** [comment]
> Hello, Toushine. I also encountered the same problem, have you solved it yet? If you successfully solve it, can you tell me the solution? thank u.
I don't know the reason.But I uninstall the mpc and all dependencies cleanly,then install the dependencies and mpc again.After that,I can run the demo without any error.So,we should  follow the installtion guide carefully and  install the dependencies correctly.Hopefully,you can get the same effect.

**Comment by Toushine** [comment]
I don't know the reason.But I uninstall the mpc and all dependencies cleanly,then install the dependencies and mpc again.After that,I can run the demo without any error.So,we should follow the installtion guide carefully and install the dependencies correctly.Hopefully,you can get the same effect.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月29日(星期三) 晚上8:35
收件人: ***@***.***&gt;; 
抄送: "浙工大 ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [rst-tu-dortmund/mpc_local_planner] Use example get the &quot;move_base-3&quot; error. (#37)





  
Hi,Christoph Rosmann. I use origion source and launch "roslaunch mpc_local_planner_examples carlike_minimum_time.launch" ,get [move_base-3] error in the end. I have installed all dependencies and catkin_make successfully.I have searched "move_base-3" error for a long time but get nothing. Could you please help me solve this issue,thank you. PS:ubuntu 18.04 ros melodic
 
[ INFO] [1618374390.653249419]: Loading map from image "/home/nical/mpc_ws/src/mpc_local_planner/mpc_local_planner_examples/maps/maze.png" [ INFO] [1618374390.687995636]: Subscribed to map topic. [ INFO] [1618374391.097138854, 0.300000000]: Read a 200 X 200 map @ 0.050 m/cell [ INFO] [1618374391.372478110, 0.500000000]: Received a 200 X 200 map @ 0.050 m/pix
 
[ INFO] [1618374391.375526743, 0.500000000]: Initializing likelihood field model; this can take some time on large maps... [ INFO] [1618374391.380459469, 0.500000000]: Done initializing likelihood field model. [ INFO] [1618374392.398645250, 1.600000000]: global_costmap: Using plugin "static_layer" [ INFO] [1618374392.421153095, 1.600000000]: Requesting the map... [ INFO] [1618374392.591438304, 1.800000000]: Resizing costmap to 200 X 200 at 0.050000 m/pix [ INFO] [1618374392.691358487, 1.900000000]: Received a 200 X 200 map at 0.050000 m/pix [ INFO] [1618374392.699597269, 1.900000000]: global_costmap: Using plugin "obstacle_layer" [ INFO] [1618374392.701547553, 1.900000000]: Subscribed to Topics: laser_scan_sensor [ INFO] [1618374392.712448318, 1.900000000]: global_costmap: Using plugin "inflation_layer" [ INFO] [1618374392.736464387, 1.900000000]: local_costmap: Using plugin "static_layer" [ INFO] [1618374392.738583883, 1.900000000]: Requesting the map... [ INFO] [1618374392.739329529, 1.900000000]: Resizing static layer to 200 X 200 at 0.050000 m/pix [ INFO] [1618374392.789361141, 2.000000000]: Received a 200 X 200 map at 0.050000 m/pix [ INFO] [1618374392.792265019, 2.000000000]: local_costmap: Using plugin "obstacle_layer" [ INFO] [1618374392.793613181, 2.000000000]: Subscribed to Topics: laser_scan_sensor [ INFO] [1618374392.816575793, 2.000000000]: Created local_planner mpc_local_planner/MpcLocalPlannerROS [ INFO] [1618374392.821068506, 2.000000000]: Footprint model 'line' (line_start: [0,0]m, line_end: [0.4,0]m) loaded for trajectory optimization. [move_base-3] process has died [pid 7319, exit code -11, cmd /home/nical/mpc_ws/devel/lib/move_base/move_base __name:=move_base __log:=/home/nical/.ros/log/95c63164-9cd9-11eb-a37b-e45e37a829c9/move_base-3.log]. log file: /home/nical/.ros/log/95c63164-9cd9-11eb-a37b-e45e37a829c9/move_base-3*.log
  
Hello, Toushine.
 I also encountered the same problem, have you solved it yet?
 If you successfully solve it, can you tell me the solution? thank u.

**Comment by Toushine** [comment]
I don't know the reason.But I uninstall the mpc and all dependencies cleanly,then install the dependencies and mpc again.After that,I can run the demo without any error.So,we should follow the installtion guide carefully and install the dependencies correctly.Hopefully,you can get the same effect.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月29日(星期三) 晚上8:35
收件人: ***@***.***&gt;; 
抄送: "浙工大 ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [rst-tu-dortmund/mpc_local_planner] Use example get the &quot;move_base-3&quot; error. (#37)





 
Hello, Toushine.
 I also encountered the same problem, have you solved it yet?
 If you successfully solve it, can you tell me the solution? thank u.

**Comment by ruficol** [comment]
> > Hello, Toushine. I also encountered the same problem, have you solved it yet? If you successfully solve it, can you tell me the solution? thank u.
> > I don't know the reason.But I uninstall the mpc and all dependencies cleanly,then install the dependencies and mpc again.After that,I can run the demo without any error.So,we should  follow the installtion guide carefully and  install the dependencies correctly.Hopefully,you can get the same effect.

Thank you for replying so quickly. I will try your method later.
