### ISSUE TITLE
move_base error

### ISSUE THREAD

**Issue by rosrookie** [rst-tu-dortmund/mpc_local_planner#53]
when i put 
`roslaunch mpc_local_planner_examples carlike_minimum_time.launch`
everything is fine, no error and warning.
but when i set a goal with 2D Nav Goal. error happens
here is the error msg:
```
[move_base-3] process has died [pid 240428, exit code -11, cmd /opt/ros/noetic/lib/move_base/move_base __name:=move_base __log:=/home/loren/.ros/log/b04678b0-fc67-11ed-bd54-d1dcc34a72bd/move_base-3.log].
log file: /home/loren/.ros/log/b04678b0-fc67-11ed-bd54-d1dcc34a72bd/move_base-3*.log
```

Dose anyone can help me out?
I use the noetic-version
Thanks

**Comment by AleksandrKashirin** [comment]
I have faced the same issue. It doesn't seem like this package still has any support.

**Comment by rosrookie** [comment]
> I have faced the same issue. It doesn't seem like this package still has any support.

Hi, AleksandrKashirin. I just fixed this issue. Here is what I do.
I build IPOPT and control_box_rst from source code with their wiki install.
Then the problem solved. But I don't know why.
