### ISSUE TITLE
problem for ipopt

### ISSUE THREAD

**Issue by sweetquiet** [rst-tu-dortmund/mpc_local_planner#7]
Hi,  I have successfully installed ipopt, but I get error: no matching function for call to ‘corbo :: SolverIpopt :: initialize ()’ when compiling
          solver-> initialize (); // requried for setting parameters afterward

Looking forward to your reply！ thank you .

**Comment by sweetquiet** [comment]
It should select [OptimizationProblemInterface* problem = nullptr](https://github.com/rst-tu-dortmund/control_box_rst/blob/ef7a2ce2f8fac93aa8bd46cc3753631515b4845e/src/optimization/include/corbo-optimization/solver/nlp_solver_ipopt.h#L65)over [OptimizationProblemInterface* problem](https://github.com/rst-tu-dortmund/control_box_rst/blob/ef7a2ce2f8fac93aa8bd46cc3753631515b4845e/src/optimization/include/corbo-optimization/solver/nlp_solver_ipopt.h#L203)

**Comment by croesmann** [comment]
Then it's not properly found by the cmake configuration. I'll add docs on compiling everything from source soon.
Have you done the following steps?:
- Download, compile and install Ipopt:

      cd /somefolder/CoinIpopt
      mkdir build
      cd build 
      ../configure --prefix=/usr/local ADD_FFLAGS=-fPIC ADD_CFLAGS=-fPIC ADD_CXXFLAGS=-fPIC
      make
      sudo make install

- Download, compile and install [control_box_rst](https://github.com/rst-tu-dortmund/control_box_rst):
  
      cd /somefolder/control_box_rst
      mkdir build
      cmake ..
      make
      sudo make install

   You should see "IPOPT found" during the call to cmake.

- Download mpc_local_planner into your catkin workspace and build everything as usual (e.g. with `catkin_make`).

This is just one way of compiling from source in which control_box_rst is not included in the catkin workspace.

**Comment by sweetquiet** [comment]
Hi ! Thank you for your reply! I already successfully installed  ipopt for sudo apt-get install coinor-libipopt-dev, but The first method caused control_box_rst not to find "IPOPT"， thanks again!
