### ISSUE TITLE
Build fails in kinetic - missing headers

### ISSUE THREAD

**Issue by beyoungglh** [rst-tu-dortmund/mpc_local_planner#8]
**when i run catkin_make, i got the following error:**
`In file included from home/glh/navigation/src/mpc_local_planner/mpc_local_planner/src/optimal_control/full_discretization_grid_base_se2.cpp:23:0:
/home/glh/navigation/src/mpc_local_planner/mpc_local_planner/include/mpc_local_planner/optimal_control/full_discretization_grid_base_se2.h:26:101: fatal error: corbo-optimal-control/structured_ocp/discretization_grids/discretization_grid_interface.h: No such file or directory
`
**and** 
`In file included from /home/glh/navigation/src/mpc_local_planner/mpc_local_planner/src/utils/publisher.cpp:23:0:
/home/glh/navigation/src/mpc_local_planner/mpc_local_planner/include/mpc_local_planner/utils/publisher.h:26:36: fatal error: corbo-core/time_series.h: No such file or directory
`

**Comment by croesmann** [comment]
I think you have not install the control_box_rst dependency properly.
Please follow the steps described [here](https://github.com/rst-tu-dortmund/control_box_rst/wiki/Build-ROS-Package#individual-build-and-install).

**Comment by beyoungglh** [comment]
thank you for your reply, i have installed control_box_rst according to your advice, but i am faced with the same problem with [this](https://answers.ros.org/question/329601/teb_local_planner-compilation-error/), maybe i should update to melodic.

**Comment by croesmann** [comment]
ah yes, the move_base API changed in lunar or melodic, especially to switch from tf1 to tf2.
It would be straightforward to "backport" the MpcLocalPlanner class/interface to be compliant with kinetic. Unfortunately, I don't have the resources to do that right now. And yes, in general I recommend to switch to melodic.
