### ISSUE TITLE
Inquiring about used "corbo" package

### ISSUE THREAD

**Issue by chameera-w** [rst-tu-dortmund/mpc_local_planner#9]
There are several packages that inherited from "corbo" has been used in mpc_local_planner package such as corbo-core, corbo-optimal-controller.

Does anyone know where to find those packages?

**Comment by croesmann** [comment]
It's the current acronym for [control_box_rst](https://github.com/rst-tu-dortmund/control_box_rst).
I still need some time to add all the documentation here and there ;-)
